.TH zergmap 1 "24 AUG 2017" "1.0" "zergmap man page"

.SH NAME
zergmap \- destroy zerg hordes

.SH SYNOPSIS
.B zergmap
...
.B [
.I PCAPS
.B ]
.B [
.I -h Health Percentage
.B ]

.SH DESCRIPTION
This manual documents the
.B zergmap
tool.
.B zergmap
finds unconnected zerg units on a battlefield and removes units that prevent a psychic wave from destroying the herd.

.SH AUTHOR
Written by Josh Abraham.

.SH REPORTING BUGS
Help at https://github.com/jabedude/

.SH COPYRIGHT
Copyright (c) 2017 Joshua Abraham MIT License
